PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/f459d558089a8a8eb2cdf95569c2679d87d8054f

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/9331fda0d7f7220de33982e8a641c671b1f09c8e) in current PX4/master (f3cd5b19c8db6e935e8fbabac312ec77861c55d9)
https://github.com/PX4/NuttX/compare/9331fda0d7f7220de33982e8a641c671b1f09c8e...f459d558089a8a8eb2cdf95569c2679d87d8054f

f459d55808 (HEAD, origin/master) Merge branch 'master' of github.com:apache/incubator-nuttx
44dcda920d boards/arm/lpc43xx/bambino-200e/src/lpc43_appinit.c:  Fix typo noted in last PR by João Matos.
e298ccef36 Merge branch 'master' of github.com:apache/incubator-nuttx
208463e7c5 boards/arm/lpc43xx/bambino-200e/src/lpc43_appinit.c: Eliminate a warning found in build testing.
afc2bffb7d net/icmpv6/icmpv6_netpoll.c: Fix two warnings found in build testing
d1bec5a6b5 Merge branch 'master' of github.com:apache/incubator-nuttx
15eddd29c8 cxd56xx improvements (#48) and various other fixes (#49)
973938dc1a Merge branch 'master' of bitbucket.org:nuttx/nuttx
c5e25dc259 Merge branch 'master' of github.com:apache/incubator-nuttx
9d5d60fee1 Run all .c and .h files in last PR49 through nxstyle.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/5c936ce0e4151115e537feba04653af667a29d93

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (f3cd5b19c8db6e935e8fbabac312ec77861c55d9)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...5c936ce0e4151115e537feba04653af667a29d93

5c936ce0 (HEAD -> master, origin/master) Various fixes (#6)
74ba8ff2 Merge pull request #5 from xiaoxiang781216/fix-void-cast
f00b4e6f Merge pull request #4 from xiaoxiang781216/fix-suffix
85715845 Unify the void cast usage
6a65664c Application.mk remove _main suffix from REGLIST
73e1696e Merge pull request #3 from xiaoxiang781216/builtin
7a645baa Add .updated target to handle the no builtin app case correctly
8c8c4813 fix builtin_list.c:58:10: fatal error: builtin_proto.h: No such file or directory (#2)
64bc8f5b Run all .c and .h files modified in last PR through nxstyle.
49c99750 Wapi simplify (#1)